[Desktop Entry]
Name=Poison
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Poison
MetacityTheme=Poison
IconTheme=Drakfire Ultra White
GtkColorScheme=fg_color:#D4D4D4,bg_color:#353535,base_color:#363636,text_color:#EFEFEF,selected_bg_color:#39FF00,selected_fg_color:#000000,tooltip_bg_color:#39ff00,tooltip_fg_color:#000000,frame_color:#C9C9C9,inactive_frame_color:#C9C9C9,scroll_color:#39FF00
CursorTheme=default
CursorSize=18
NotificationTheme=ubuntu
